spring.application.name=backend

# postgresql configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tutoring_db
spring.datasource.username=jiaerc
spring.datasource.password=zxcvbnm147258
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis-Plus configuration
mybatis-plus.mapper-locations=classpath:sql/*.xml
mybatis-plus.type-aliases-package=com.tutoring_software.backend.uid_management.entity
mybatis-plus.configuration.map-underscore-to-camel-case=true